// AUTO-GENERATED by scripts/split-exercise-images.py — do not edit manually.
// Maps exerciseId → array of require() sources for each step image.

import type { ImageSource } from "expo-image";

const placeholder = require("../../assets/images/exercises/placeholder.png");

const map: Record<string, ImageSource[]> = {
  "ankle-circles": [require("../../assets/images/exercises/ankle-circles/step-1.png"), require("../../assets/images/exercises/ankle-circles/step-2.png"), require("../../assets/images/exercises/ankle-circles/step-3.png"), require("../../assets/images/exercises/ankle-circles/step-4.png")],
  "bicycle-crunches": [require("../../assets/images/exercises/bicycle-crunches/step-1.png"), require("../../assets/images/exercises/bicycle-crunches/step-2.png"), require("../../assets/images/exercises/bicycle-crunches/step-3.png"), require("../../assets/images/exercises/bicycle-crunches/step-4.png")],
  "bird-dog": [require("../../assets/images/exercises/bird-dog/step-1.png"), require("../../assets/images/exercises/bird-dog/step-2.png"), require("../../assets/images/exercises/bird-dog/step-3.png"), require("../../assets/images/exercises/bird-dog/step-4.png"), require("../../assets/images/exercises/bird-dog/step-5.png")],
  "bodyweight-squats": [require("../../assets/images/exercises/bodyweight-squats/step-1.png"), require("../../assets/images/exercises/bodyweight-squats/step-2.png"), require("../../assets/images/exercises/bodyweight-squats/step-3.png"), require("../../assets/images/exercises/bodyweight-squats/step-4.png"), require("../../assets/images/exercises/bodyweight-squats/step-5.png")],
  "burpees": [require("../../assets/images/exercises/burpees/step-1.png"), require("../../assets/images/exercises/burpees/step-2.png"), require("../../assets/images/exercises/burpees/step-3.png"), require("../../assets/images/exercises/burpees/step-4.png"), require("../../assets/images/exercises/burpees/step-5.png"), require("../../assets/images/exercises/burpees/step-6.png")],
  "butt-kicks": [require("../../assets/images/exercises/butt-kicks/step-1.png"), require("../../assets/images/exercises/butt-kicks/step-2.png"), require("../../assets/images/exercises/butt-kicks/step-3.png")],
  "calf-raises": [require("../../assets/images/exercises/calf-raises/step-1.png"), require("../../assets/images/exercises/calf-raises/step-2.png"), require("../../assets/images/exercises/calf-raises/step-3.png"), require("../../assets/images/exercises/calf-raises/step-4.png")],
  "cat-cow": [require("../../assets/images/exercises/cat-cow/step-1.png"), require("../../assets/images/exercises/cat-cow/step-2.png"), require("../../assets/images/exercises/cat-cow/step-3.png"), require("../../assets/images/exercises/cat-cow/step-4.png")],
  "chair-tricep-dips": [require("../../assets/images/exercises/chair-tricep-dips/step-1.png"), require("../../assets/images/exercises/chair-tricep-dips/step-2.png"), require("../../assets/images/exercises/chair-tricep-dips/step-3.png"), require("../../assets/images/exercises/chair-tricep-dips/step-4.png")],
  "childs-pose": [require("../../assets/images/exercises/childs-pose/step-1.png"), require("../../assets/images/exercises/childs-pose/step-2.png"), require("../../assets/images/exercises/childs-pose/step-3.png"), require("../../assets/images/exercises/childs-pose/step-4.png"), require("../../assets/images/exercises/childs-pose/step-5.png")],
  "chin-tucks": [require("../../assets/images/exercises/chin-tucks/step-1.png"), require("../../assets/images/exercises/chin-tucks/step-2.png"), require("../../assets/images/exercises/chin-tucks/step-3.png"), require("../../assets/images/exercises/chin-tucks/step-4.png")],
  "cobra-pose": [require("../../assets/images/exercises/cobra-pose/step-1.png"), require("../../assets/images/exercises/cobra-pose/step-2.png"), require("../../assets/images/exercises/cobra-pose/step-3.png"), require("../../assets/images/exercises/cobra-pose/step-4.png"), require("../../assets/images/exercises/cobra-pose/step-5.png")],
  "dead-bug": [require("../../assets/images/exercises/dead-bug/step-1.png"), require("../../assets/images/exercises/dead-bug/step-2.png"), require("../../assets/images/exercises/dead-bug/step-3.png"), require("../../assets/images/exercises/dead-bug/step-4.png")],
  "decline-push-ups": [require("../../assets/images/exercises/decline-push-ups/step-1.png"), require("../../assets/images/exercises/decline-push-ups/step-2.png"), require("../../assets/images/exercises/decline-push-ups/step-3.png"), require("../../assets/images/exercises/decline-push-ups/step-4.png")],
  "diamond-push-ups": [require("../../assets/images/exercises/diamond-push-ups/step-1.png"), require("../../assets/images/exercises/diamond-push-ups/step-2.png"), require("../../assets/images/exercises/diamond-push-ups/step-3.png")],
  "doorway-chest-stretch": [require("../../assets/images/exercises/doorway-chest-stretch/step-1.png"), require("../../assets/images/exercises/doorway-chest-stretch/step-2.png"), require("../../assets/images/exercises/doorway-chest-stretch/step-3.png"), require("../../assets/images/exercises/doorway-chest-stretch/step-4.png")],
  "downward-dog": [require("../../assets/images/exercises/downward-dog/step-1.png"), require("../../assets/images/exercises/downward-dog/step-2.png"), require("../../assets/images/exercises/downward-dog/step-3.png"), require("../../assets/images/exercises/downward-dog/step-4.png"), require("../../assets/images/exercises/downward-dog/step-5.png")],
  "eye-20-20-20": [require("../../assets/images/exercises/eye-20-20-20/step-1.png"), require("../../assets/images/exercises/eye-20-20-20/step-2.png"), require("../../assets/images/exercises/eye-20-20-20/step-3.png")],
  "neck-rolls": [require("../../assets/images/exercises/neck-rolls/step-1.png"), require("../../assets/images/exercises/neck-rolls/step-2.png"), require("../../assets/images/exercises/neck-rolls/step-3.png"), require("../../assets/images/exercises/neck-rolls/step-4.png")],
  "shoulder-rolls": [require("../../assets/images/exercises/shoulder-rolls/step-1.png"), require("../../assets/images/exercises/shoulder-rolls/step-2.png"), require("../../assets/images/exercises/shoulder-rolls/step-3.png")],
};

export function getExerciseStepImages(exerciseId: string): ImageSource[] | null {
  return map[exerciseId] ?? null;
}

export function getPlaceholderImage(): ImageSource {
  return placeholder;
}
