// AUTO-GENERATED by scripts/split-exercise-images.py — do not edit manually.
// Maps exerciseId → array of require() sources for each step image.

import { ImageSource } from "expo-image";

// eslint-disable-next-line @typescript-eslint/no-var-requires
const placeholder = require("../../assets/images/exercises/placeholder.png");

const map: Record<string, ImageSource[]> = {
  "neck-rolls": [require("../../assets/images/exercises/neck-rolls/step-1.png"), require("../../assets/images/exercises/neck-rolls/step-2.png"), require("../../assets/images/exercises/neck-rolls/step-3.png"), require("../../assets/images/exercises/neck-rolls/step-4.png")],
};

export function getExerciseStepImages(exerciseId: string): ImageSource[] | null {
  return map[exerciseId] ?? null;
}

export function getPlaceholderImage(): ImageSource {
  return placeholder;
}
