"""CLI: python inspect_rig.py <rig.blend> [> output.md]

Opens a Mixamo .blend rig in Blender background mode and prints a markdown
axis-calibration table to stdout.  Run this BEFORE authoring pose values for
any new exercise — translation channels (loc_X/Y/Z) move along the bone's
LOCAL axes, which differ from world axes in non-obvious ways.

Usage:
    python3 scripts/inspect_rig.py assets/blender/xbot_rigged.blend > assets/blender/xbot_rig_axes.md
    BLENDER_BIN=/path/to/blender python3 scripts/inspect_rig.py ...

Mirror pattern from animate.py: re-exec via blender --background when
running outside of Blender.
"""
import os
import sys
from pathlib import Path


def _running_in_blender() -> bool:
    try:
        import bpy  # noqa
        return True
    except ImportError:
        return False


SCRIPTS_DIR = Path(__file__).parent
APP_DIR = SCRIPTS_DIR.parent

# Curated list of Mixamo bones to inspect (without the mixamorig: prefix).
# Script adds the prefix automatically.
BONE_GROUPS = {
    "Root and spine": [
        "Hips", "Spine", "Spine1", "Spine2", "Neck", "Head",
    ],
    "Left arm chain": [
        "LeftShoulder", "LeftArm", "LeftForeArm", "LeftHand",
    ],
    "Right arm chain": [
        "RightShoulder", "RightArm", "RightForeArm", "RightHand",
    ],
    "Left leg chain": [
        "LeftUpLeg", "LeftLeg", "LeftFoot", "LeftToeBase",
    ],
    "Right leg chain": [
        "RightUpLeg", "RightLeg", "RightFoot", "RightToeBase",
    ],
    "Fingers (left hand — mirror for right)": [
        "LeftHandIndex1", "LeftHandIndex2", "LeftHandIndex3",
        "LeftHandMiddle1", "LeftHandMiddle2", "LeftHandMiddle3",
        "LeftHandRing1", "LeftHandRing2", "LeftHandRing3",
        "LeftHandPinky1", "LeftHandPinky2", "LeftHandPinky3",
        "LeftHandThumb1", "LeftHandThumb2", "LeftHandThumb3",
    ],
}

MIXAMO_PREFIX = "mixamorig:"


def _label(v, threshold=0.85):
    """Return a plain-English label for a world-space unit vector.

    Picks the dominant component (magnitude > threshold after normalisation).
    If none dominates, returns '(skewed) <raw vector>'.
    """
    import mathutils  # available inside Blender
    v = v.normalized()
    labels = {
        (0, 1): "+X (lateral right)",
        (0, -1): "-X (lateral left)",
        (1, 1): "+Y (back)",
        (1, -1): "-Y (forward)",
        (2, 1): "+Z (up)",
        (2, -1): "-Z (down)",
    }
    for i in range(3):
        c = v[i]
        if abs(c) >= threshold:
            sign = 1 if c > 0 else -1
            return labels[(i, sign)]
    return f"(skewed) ({v.x:.2f}, {v.y:.2f}, {v.z:.2f})"


def _bone_direction(armature, pose_bone):
    """Return head→tail unit vector in world space."""
    import mathutils
    mat = armature.matrix_world
    head_w = mat @ pose_bone.bone.head_local
    tail_w = mat @ pose_bone.bone.tail_local
    delta = tail_w - head_w
    if delta.length < 1e-6:
        return mathutils.Vector((0, 0, 1))
    return delta.normalized()


def _is_twist_axis(axis_vec, bone_dir, threshold=0.95):
    """True if the local axis is nearly parallel to the bone's length."""
    import mathutils
    return abs(axis_vec.normalized().dot(bone_dir)) >= threshold


def main_in_blender(rig_path: str) -> int:
    import bpy
    import mathutils

    # Silence Blender's console noise on stdout by redirecting at fd level.
    # We write our output to a separate fd, then restore after.
    import io

    # Open the rig file.
    bpy.ops.wm.open_mainfile(filepath=rig_path)

    armature = next((o for o in bpy.data.objects if o.type == "ARMATURE"), None)
    if armature is None:
        print(f"ERROR: no armature in {rig_path}", file=sys.stderr)
        return 1

    # Ensure pose mode so pose_bone axes are available.
    bpy.context.view_layer.objects.active = armature

    rig_filename = Path(rig_path).name
    lines = []

    lines.append(f"# Rig axis calibration — {rig_filename}")
    lines.append("")
    lines.append(
        "Generated by `scripts/inspect_rig.py`. Each row shows the world-space direction"
    )
    lines.append(
        "of the bone's local axes at rest pose. Use this BEFORE writing pose values for"
    )
    lines.append("a new exercise.")
    lines.append("")
    lines.append("## Conventions")
    lines.append("")
    lines.append(
        "World axes (Blender default, Z-up): +X = character right, -Y = character forward, +Z = up."
    )
    lines.append("")

    # Collect per-bone data for the rotation-examples section later.
    arm_examples = []   # (bone_name, direction_label, local_axes_labels)
    bone_data = {}      # bone_name -> {x_label, y_label, z_label, dir_label, x_vec, y_vec, z_vec, dir_vec}

    for section, bone_names in BONE_GROUPS.items():
        lines.append(f"## {section}")
        lines.append("")
        lines.append("| Bone | Bone points | Local X | Local Y | Local Z |")
        lines.append("|------|-------------|---------|---------|---------|")

        for short_name in bone_names:
            full_name = MIXAMO_PREFIX + short_name
            pose_bone = armature.pose.bones.get(full_name)
            if pose_bone is None:
                lines.append(f"| `{short_name}` | *(not found)* | — | — | — |")
                continue

            # World-space axes: pose_bone.x_axis etc. are already in world space
            # (they account for the armature world matrix and current pose).
            # At rest pose (T-pose) these equal the bind-pose orientation.
            x_ax = pose_bone.x_axis.copy()
            y_ax = pose_bone.y_axis.copy()
            z_ax = pose_bone.z_axis.copy()
            dir_vec = _bone_direction(armature, pose_bone)

            x_lbl = _label(x_ax)
            y_lbl = _label(y_ax)
            z_lbl = _label(z_ax)
            dir_lbl = _label(dir_vec)

            bone_data[short_name] = dict(
                x_label=x_lbl, y_label=y_lbl, z_label=z_lbl,
                dir_label=dir_lbl,
                x_vec=x_ax, y_vec=y_ax, z_vec=z_ax, dir_vec=dir_vec,
            )

            lines.append(
                f"| `{short_name}` | {dir_lbl} | {x_lbl} | {y_lbl} | {z_lbl} |"
            )

        lines.append("")

    # ── Translation gotcha section ────────────────────────────────────────────
    lines.append("## Translation (location) channels")
    lines.append("")
    lines.append(
        "`loc_X`, `loc_Y`, `loc_Z` on a pose bone translate the bone along its OWN LOCAL "
        "axes — **not** along world X/Y/Z. This is the most common gotcha: "
        "a beginner reaches for `loc_Z` to move the character up/down, but on the "
        "Hips bone the Z local axis may point world-forward, not world-up."
    )
    lines.append("")
    lines.append(
        "Mapping derived from this rig (rest pose, armature world matrix = identity):"
    )
    lines.append("")
    lines.append("| Bone | loc_X moves body in | loc_Y moves body in | loc_Z moves body in |")
    lines.append("|------|---------------------|---------------------|---------------------|")

    for short_name in ["Hips", "Spine", "Spine1", "Spine2"]:
        d = bone_data.get(short_name)
        if d:
            lines.append(
                f"| `{short_name}` | {d['x_label']} | {d['y_label']} | {d['z_label']} |"
            )

    lines.append("")
    lines.append(
        "> **Rule:** before writing any `loc_*` value, look up the bone row above and "
        "identify which local axis maps to world `+Z (up)`. That is your vertical-bounce channel."
    )
    lines.append("")

    # Highlight the Hips gotcha explicitly.
    hips = bone_data.get("Hips")
    if hips:
        up_channel = None
        for ch, vec in [("loc_X", hips["x_vec"]), ("loc_Y", hips["y_vec"]), ("loc_Z", hips["z_vec"])]:
            if _label(vec) == "+Z (up)":
                up_channel = ch
                break
        if up_channel:
            lines.append(
                f"> **Hips vertical bounce:** use `{up_channel}` (not the other two). "
                f"`{up_channel}` is the world-up axis on this rig."
            )
            lines.append("")

    # ── Rotation channels section ─────────────────────────────────────────────
    lines.append("## Rotation channels")
    lines.append("")
    lines.append(
        "**Important caveat:** twist vs swing depends on the bone's CURRENT pose, not just "
        "rest pose. When a bone is first rotated into a working position (e.g. the arm bone "
        "rotated X+90° to hang at the side), ALL its local axes rotate with it, so what was "
        "the twist axis at rest may become the swing axis in the working pose. The rest-pose "
        "table above shows where local axes point at T-pose; in practice always verify with "
        "`--frame <peak>` for any bone that has a baseline rotation before animation begins."
    )
    lines.append("")
    lines.append(
        "The geometric rule: if a local axis aligns with the bone's own length (head→tail) "
        "at the CURRENT pose, rotating around it is a TWIST. The other two produce swing. "
        "Below are three examples using rest-pose geometry (valid for Spine and leg bones "
        "that animate near rest; arm bones have a baseline X+90° offset, see note above)."
    )
    lines.append("")
    lines.append("Three concrete examples from this rig (rest-pose geometry):")
    lines.append("")

    # Only use bones that animate near rest pose (spine, leg).
    # Arm bones have a baseline X=90° offset that invalidates rest-pose twist analysis.
    rest_pose_bones = ["LeftUpLeg", "Spine"]
    for short_name in rest_pose_bones:
        d = bone_data.get(short_name)
        if not d:
            continue
        dir_vec = d["dir_vec"]
        dir_lbl = d["dir_label"]
        axes = [
            ("X", d["x_vec"], d["x_label"]),
            ("Y", d["y_vec"], d["y_label"]),
            ("Z", d["z_vec"], d["z_label"]),
        ]
        twist_axes = []
        swing_axes = []
        for ax_name, ax_vec, ax_lbl in axes:
            if _is_twist_axis(ax_vec, dir_vec):
                twist_axes.append((ax_name, ax_lbl))
            else:
                swing_axes.append((ax_name, ax_lbl))

        lines.append(f"### `{short_name}` (rest-pose analysis valid)")
        lines.append("")
        lines.append(f"Bone points {dir_lbl} at rest — this is also the working pose.")
        lines.append("")
        for ax_name, ax_lbl in twist_axes:
            lines.append(
                f"- **Local {ax_name}** ({ax_lbl}) — parallel to bone length → "
                f"**TWIST around bone's length.** Spins in place; does not swing the bone direction."
            )
        for ax_name, ax_lbl in swing_axes:
            lines.append(
                f"- **Local {ax_name}** ({ax_lbl}) — perpendicular to bone → "
                f"**sweep / flexion axis.** Swings the bone direction."
            )
        lines.append("")

    # Arm bones: special note because they have a baseline X=90° offset.
    arm_note_bone = "LeftArm"
    d = bone_data.get(arm_note_bone)
    if d:
        lines.append(f"### `LeftArm` (working-pose analysis — rest-pose geometry is misleading here)")
        lines.append("")
        lines.append(
            f"At T-pose rest, the bone points {d['dir_label']} and local Y also aligns with "
            f"the bone (+X lateral right), which would geometrically identify Y as twist. "
            f"**But** the arm is always first rotated X+90° to hang at the character's side "
            f"before any animation begins. In that working position the arm points world -Z (down), "
            f"and all local axes have rotated 90° with it:"
        )
        lines.append("")
        lines.append(
            "- **Local Y** — in working pose (arm at side): **forward/back sagittal swing axis.** "
            "Verified empirically: Y-45° moves the forearm forward (world -Y direction). "
            "This is the running-arm swing axis used by `high_knees.py`."
        )
        lines.append(
            "- **Local Z** — in working pose (arm at side): **TWIST around bone length** "
            "(arm now points -Z; Z becomes the bone-length axis). Produces outward forearm sweep — "
            "NOT sagittal swing. Avoid for running-arm motion."
        )
        lines.append(
            "- **Local X** — abduction/adduction (arm swings toward/away from the body midline "
            "in the frontal plane). Used as the T-pose-to-at-side baseline (X+90° = arm hangs down)."
        )
        lines.append("")

    lines.append(
        "> **Rule of thumb:** for spine and leg bones that animate near T-pose, read the "
        "\"Bone points\" column — the local axis that matches it is TWIST, the other two sweep. "
        "For arm bones with a baseline X+90° offset, the working-pose semantics are: "
        "**Y = sagittal swing, Z = twist around length, X = abduction**. Always verify with "
        "`python3 scripts/animate.py <exercise> --frame <peak>` before committing pose values."
    )
    lines.append("")

    # Print everything to stdout.
    print("\n".join(lines))
    return 0


def main_outside_blender(rig_path: str) -> int:
    """Re-exec via `blender --background --python this_file -- <rig_path>`."""
    import subprocess
    blender = os.environ.get("BLENDER_BIN", "blender")
    cmd = [
        blender,
        "--background",
        "--python", str(__file__),
        "--",
        rig_path,
    ]
    # Blender writes its startup banner and "Read blend:" lines to stdout even
    # in background mode.  We strip everything before the first line that starts
    # with '#' (our markdown heading sentinel) so the output is clean markdown.
    result = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

    raw = result.stdout.decode("utf-8", errors="replace")
    all_lines = raw.splitlines(keepends=True)

    # Blender writes startup noise (version banner, "Read prefs:", "Read blend:",
    # "Blender quit") to stdout interleaved with our output.  Strip those lines
    # wherever they appear.  Our markdown lines all start with printable non-
    # whitespace that is NOT the patterns Blender uses.
    _BLENDER_NOISE = (
        "Blender ",
        "Read prefs:",
        "Read blend:",
        "Blender quit",
        "Fra:",
        "Saved:",
        "Warning:",
        "Found ",
        "AL lib:",
    )

    clean_lines = []
    seen_heading = False
    for line in all_lines:
        stripped = line.lstrip()
        is_noise = any(stripped.startswith(p) for p in _BLENDER_NOISE)
        if not seen_heading:
            if stripped.startswith("#"):
                seen_heading = True
            else:
                continue  # skip everything before first heading
        if not is_noise:
            clean_lines.append(line)

    clean = "".join(clean_lines)
    sys.stdout.write(clean)
    sys.stdout.flush()

    # Only forward Blender stderr if something went wrong, so it doesn't
    # contaminate the markdown output when the user redirects stdout to a file.
    if result.returncode != 0:
        sys.stderr.buffer.write(result.stderr)
        sys.stderr.buffer.flush()
    return result.returncode


if __name__ == "__main__":
    if _running_in_blender():
        if "--" in sys.argv:
            argv = sys.argv[sys.argv.index("--") + 1:]
        else:
            argv = sys.argv[1:]
        if not argv:
            print("Usage: inspect_rig.py <rig.blend>", file=sys.stderr)
            sys.exit(1)
        sys.exit(main_in_blender(argv[0]))
    else:
        if len(sys.argv) < 2:
            print("Usage: python3 scripts/inspect_rig.py <rig.blend> [> output.md]", file=sys.stderr)
            sys.exit(1)
        sys.exit(main_outside_blender(sys.argv[1]))
